apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  serviceName: postgres-svc
  selector:
    matchLabels:
      app: postgres-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: {{ .Values.keycloak.postgres.statefulset.image }}:{{ .Values.keycloak.postgres.statefulset.tag }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: postgres-credentials
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/db
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
