# Default values for kibo-scylla.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Suite Name
name: kibo

# Operating Domain
domain: kibo.org

scylla:
  statefulset:
    setName: scylla-set
    serviceName: scylla-svc
    replicas: 3
    image: scylladb/scylla
    tag: 5.2.0
  hostMountPath: /run/desktop/mnt/scylla # Docker Desktop specific path
  storage:
    class: hostpath
    size: 1Gi
