apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylla-data-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/scylla"