apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.scylla.statefulset.serviceName }}
  labels:
    app: {{ .Values.scylla.statefulset.setName }}
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: scylla-port
  selector:
    app: {{ .Values.scylla.statefulset.setName }}
