cluster_name: 'Test Cluster'

num_tokens: 256

commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000

commitlog_segment_size_in_mb: 32

seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "127.0.0.1"

listen_address: localhost

native_transport_port: 9042
native_shard_aware_transport_port: 19042

read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
cas_contention_timeout_in_ms: 1000

endpoint_snitch: SimpleSnitch

rpc_address: localhost
rpc_port: 9160

api_port: 10000

api_address: 127.0.0.1

batch_size_warn_threshold_in_kb: 128

batch_size_fail_threshold_in_kb: 1024

partitioner: org.apache.cassandra.dht.Murmur3Partitioner

commitlog_total_space_in_mb: -1

consistent_cluster_management: true
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/
