apiVersion: v1
kind: Service
metadata:
  name: scylla-0
  labels:
    app: scylla-entry-node
spec:
  type: LoadBalancer
  ports:
  - port: 9042
    protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: scylla-set-0