apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
spec:
  ingressClassName: nginx-ingress-class
  tls:
    - hosts:
        - kibo.org
      secretName: kibo-selfsigned-cert-secret # Set-up here auth\cert\kibo-selfsigned-cert-secret.yaml
  rules:
    - host: kibo.org # A locally defined hostname
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: keycloak-svc
                port:
                  number: 80 # The port number exposed by the service, not necessarily the container port
