apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
spec:
  ports:
    - name: keycloak-svc-http
      port: 80
      targetPort: keycloak-http
    - name: keycloak-svc-https
      port: 443
      targetPort: keycloak-https
  selector:
    suite: keycloak-suite
  type: ClusterIP
