- hosts: core 
  become: yes
  tasks:
    - name: Create a unix group called ansible 
      group:
        name: ansible 
        state: present

    - name: Create a user called ansible
      user:
        name: ansible
        state: present
        shell: /bin/bash
        home: /home/ansible

    - name: Add ansible user to ansible group
      user:
        name: ansible
        groups: ansible 
        append: yes
      when: "'ansible' in groups"
    
    - name: Add ansible user to docker group
      user:
        name: ansible
        groups: docker
        append: yes
      when: "'docker' in groups"

    - name: Add ansible user to sudo group
      user:
        name: ansible
        groups: sudo 
        append: yes
      when: "'sudo' in groups"
