- name: Mount NVMe devices and update fstab
  hosts: filesys 
  become: true

  tasks:
    - name: Get user info
      shell: id fsadm | awk '{print $1}'
      register: user_info

    - name: fsadm User check
      fail:
        msg: "User [fsadm] must exist and have UID = 2000"
      when: "'2000' not in user_info.stdout_lines[0]"

    - name: Get fsdam group info
      command: getent group fsadm
      register: group_info

    - name: fsadm group check
      fail:
        msg: "Group [fsadm] must exist and have GID = 2000"
      when: "'2000' not in group_info.stdout_lines[0]"

    - name: Get fsusr group info
      command: getent group fsusr
      register: group_info

    - name: fsusr group check
      fail:
        msg: "Group [fsusr] must exist and have GID = 2001"
      when: "'2001' not in group_info.stdout_lines[0]"

    - name: Find NVMe devices
      shell: lsblk -d -n -o NAME,TYPE | grep nvme | awk '{print $1}'
      register: nvme_devices

    - name: Mount NVMe devices
      mount:
        name: "/mnt/{{ item }}"
        src: "/dev/{{ item }}"
        fstype: ext4
        state: mounted
      loop: "{{ nvme_devices.stdout_lines }}"

    - name: Update fstab
      lineinfile:
        path: /etc/fstab
        line: "/dev/{{ item }} /mnt/{{ item }} ext4 defaults 0 0"
      loop: "{{ nvme_devices.stdout_lines }}"

    - name: fsadm must be the owner of all shared file systems 
      file:
        path: "/mnt/{{ item }}"
        owner: fsadm 
        group: fsusr 
        mode: "770" 
        state: directory
      loop: "{{ nvme_devices.stdout_lines }}"
