apiVersion: v1
kind: Service
metadata:
  labels:
    app: scylla
  name: scylla
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 9042
      targetPort: 9042
  selector:
    app: scylla
